apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: ai-joke-teller
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
      - name: BP_JVM_VERSION
        value: "21"
      - name: BP_GRADLE_BUILT_MODULE
        value: ./applications/ai-server
    path: ../..
  ports:
  - name: main
    port: 8080
